# Generated by Django 4.0.4 on 2022-05-25 19:48

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Tecnologia',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='docente_teorica',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='ranking',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='webPage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(default='foto.png', upload_to=portfolio.models.resolution_path),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
