# Generated by Django 4.0.4 on 2022-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tfcsdeisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfcsdeisi',
            name='data',
        ),
        migrations.AddField(
            model_name='tfcsdeisi',
            name='ano',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022')], default='2021'),
        ),
    ]
